### PR TITLE
Added new 15 activities.

### PR DESCRIPTION
**Pull request by ghost**
I have decided to update the command and decided to add 15 activities to the bot.

### CODE REVIEW

**Comment by ghost** [comment]
I will add more if it's okay with you and pleas let me know if it is working or if I enter the wrong id of the game.

**Comment by ghost** [comment]
## New Activities that I added are:

- [x] Watch Together
- [x] Sketch Heads
- [x] Know What I Meme (New!)
- [x] Ask Away (New!)
- [x] Word Snacks
- [x] Bash Out (New! Requires Boost Level 1)
- [x] Bobble League (Requires Boost Level 1)
- [x] Poker Night (Requires Boost Level 1)
- [x] Putt Party (Requires Boost Level 1)
- [x] Land-io (Requires Boost Level 1)
- [x] Blazing 8s (Requires Boost Level 1)
- [x] Chess In The Park (Requires Boost Level 1)
- [x] SpellCast (Requires Boost Level 1)
- [x] Letter League (Requires Boost Level 1)
- [x] Checkers In The Park (Requires Boost Level 1)

Some activities have I removed because some of them where deleted by discord or they don't work anymore. 

I got all the games id here if you wanted to know where I got all of them: 
https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad

**Comment by Monochromish** [comment]
Will go thru it soon

**Comment by Monochromish** [comment]
@AnthonyVanTonder you've completely removed the command file, if you're not done with this pr, mark it as draft and ping me once ready to be reviewed.

**Pull request closed without merging**
